export enum Role {
  ADMIN = 'ADMIN',
  MANAGER = 'MANAGER',
  CLIENT = 'CLIENT',
  RECEPTIONIST = 'RECEPTIONIST',
  VETERINARIAN = 'VETERINARIAN',
  GROOMER = 'GROOMER',
  NOT_INFORMED = 'NOT_INFORMED'
}
